website/main/urls.py
from django.urls import path


from . import views


app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

website/news/urls.py
from django.urls import path


from . import views

app_name = 'news'

urlpatterns = [
    path('news/', views.news, name='news'),
    path('news/<int:pk>/', views.detail, name='detail'),
    path('add_news/', views.add_news, name='add_news'),
    path('news/edit/<int:pk>/', views.edit, name='edit'),
    path('news/delete/<int:pk>/', views.delete, name='delete'),

]

website/profiles/urls.py
from django.urls import path


from . import views

app_name = 'profile'

urlpatterns = [
    path('profile/', views.profile, name='profile'),
]

website/stores/urls.py
from django.urls import path


from . import views

app_name = 'stores'

urlpatterns = [
    path('stores/', views.stores, name='stores'),
    path('add_store/', views.addin_store, name='add_store'),
    path('stores/edit/<int:pk>/', views.edit, name='edit'),
    path('stores/delete/<int:pk>/', views.delete, name='delete'),
]

website/users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.custom_login, name='login'),
    path('logout/', views.custom_logout, name='logout'),
    path('employees/', views.employess, name='employees'),
    path('add_user/', views.add_user, name='add_user'),


]

website/website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('users.urls')),
    path('', include('main.urls')),
    path('', include('news.urls')),
    path('', include('stores.urls')),
    path('', include('profiles.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/main/models.py
from django.db import models

website/main/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required


@login_required
def home(request):
    return render(request, 'main/home.html')

website/main/templates/main/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title> | {% block title %}{% endblock title %}</title>
    <style>body{background-color: rgb(255, 255, 255);}</style>
</head>
<body>

  <nav class="navbar navbar-expand-lg" style="background-color: #e3f2fd;">
    <div class="container-fluid py-2 px-4">
      <a class="navbar-brand" href="#">Website</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'main:home' %}">Home</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Dropdown
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'users:employees' %}">Employees</a></li>
              <li><a class="dropdown-item" href="{% url 'stores:stores' %}">Stores</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{% url 'news:news' %}">News</a></li>
            </ul>
          </li>
        </ul>
          <a href="{% url 'profile:profile' %}"><button class="btn btn-outline-success" type="submit">Profile</button></a>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:login' %}">Login</a>
          </li>
          {% endif %}
        </div>
    </div>
  </nav>



    {% block content %}{% endblock %}
    <foote class="container-fluid fixed-bottom text-center p-2 mt-5 "style="background-color: #e3f2fd;">
        Copyright : 2023 || Develop by: behzad jalili
    </foote>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
            integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"
            integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>

</body>
</html>

website/main/templates/main/home.html
{% extends 'main/base.html' %}

{% block title %}  {% endblock %}

{% block content %}
<div class='text-dark p-3'>
    <h1>Hello {{ request.user.username}}</h1>
</div>
{% endblock %}