website/main/urls.py
from django.urls import path


from . import views


app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

website/news/urls.py
from django.urls import path


from . import views

app_name = 'news'

urlpatterns = [
    path('news/', views.news, name='news'),
    path('news/<int:pk>/', views.detail, name='detail'),
    path('add_news/', views.add_news, name='add_news'),
    path('news/edit/<int:pk>/', views.edit, name='edit'),
    path('news/delete/<int:pk>/', views.delete, name='delete'),

]

website/website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('users.urls')),
    path('', include('main.urls')),
    path('', include('news.urls')),
    path('', include('stores.urls')),
    path('', include('profiles.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/news/models.py
from django.db import models

from users.models import CustomUser

class News(models.Model):
    title = models.CharField(max_length=20)
    description = models.CharField(max_length=255)
    text = models.TextField()
    news_image = models.ImageField(upload_to='meida/images/news', null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(CustomUser, related_name='news', on_delete=models.CASCADE)

    class Meta:
        ordering = ('-created_at',)

    def __str__(self) -> str:
        return self.title

website/news/forms.py
from django import forms


from .models import News

CLASS_INPUT = 'form-control w-full rounded-xl border mb-4 mt-2'

class NewsForm(forms.ModelForm):
    class Meta:
        model = News
        fields = ['title', 'description', 'text', 'news_image']


        widgets = {
            'title': forms.TextInput(attrs={
            'class': CLASS_INPUT
            }),

            'description': forms.TextInput(attrs={
            'class': CLASS_INPUT
            }),

            'text': forms.Textarea(attrs={
            'class': CLASS_INPUT
            }),

            'news_image': forms.FileInput(attrs={
            'class': CLASS_INPUT
            }),
        }

website/news/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required

from .forms import NewsForm
from .models import News


@login_required
def news(request):
    if not request.user.is_authenticated:
        return redirect('main:home')
    
    news = News.objects.all()

    return render(request, 'news/news.html', {
        'news': news
    })


@login_required
def add_news(request):

    title = 'Add news'

    if not request.user.is_authenticated:
        return redirect('/')
    
    if request.method == 'POST':
        form = NewsForm(request.POST, request.FILES)

        if form.is_valid():
            news = form.save(commit=False)
            news.created_by = request.user
            news.save()

            return redirect('news:news')
    else:
        form = NewsForm()
    
    return render(request, 'news/add_news.html', {
        'form': form,
        'title': title,
    })


@login_required
def detail(request, pk):
    news = get_object_or_404(News, pk=pk)

    return render(request, 'news/detail.html', {
        'news': news,
    })


@login_required
def edit(request, pk):

    title = 'Edit'

    if not request.user.is_authenticated:
        return redirect('news:detail', pk=pk)
    
    news = get_object_or_404(News, pk=pk, created_by=request.user)

    if request.method == 'POST':
        form = NewsForm(request.POST, request.FILES, instance=news)

        if form .is_valid():
            form.save()

            return redirect('news:detail', pk=pk)
    else:
        form = NewsForm(instance=news)

    return render(request, 'news/add_news.html', {
        'form': form,
        'title': title,
    })


@login_required
def delete(request, pk):
    if not request.user.is_authenticated:
        return redirect('news:detail', pk=pk)
    
    news = get_object_or_404(News, pk=pk, created_by=request.user)
    news.delete()
    return redirect('news:news')

website/news/templates/news/add_news.html
{% extends 'main/base.html' %}

{% block title %} {{ title }} {% endblock %}

{% block content %}


{% if request.user.rol.name == 'system_admin' %}
<div class="mb-3">
    <div class="px-4 py-4">
        <h1>{{ title }}</h1>
        <hr>
        <form method="POST" action="." enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
        
            <button class="btn btn-outline-primary mt-2 mx-4" type="submit">confirm</button>
        </form>
    </div>
</div>
<br>
{% else %}
<h1>{{ request.user.username }} you can't add news</h1>
{% endif %}
{% endblock %}

website/news/templates/news/detail.html
{% extends 'main/base.html' %}

{% block title %} Detail {% endblock %}
{% block content %}
<div class="container text-center py-4">
    <div class="card" style="width: 100%;">
        <img src="{{ news.news_image.url }}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">{{ news.title }}</h5>
          <p class="card-text">{{ news.text }}</p>
          <br><br>
          <hr>
          <p class="card-text">{{ news.created_at }}</p>
          <a href="{% url 'news:news' %}" class="btn btn-primary">back</a>
          {% if request.user.rol.name == 'system_admin' and request.user == news.created_by %}
          <hr>
          <a href="{% url 'news:edit' news.id %}" class="btn btn-success">Edit</a>
          <a href="{% url 'news:delete' news.id %}" class="btn btn-danger">Delete</a>
          {% endif %}
        </div>
    </div>
</div>
<br><br><br>
{% endblock %}

website/news/templates/news/news.html
{% extends 'main/base.html' %}

{% block title %} News {% endblock %}

{% block content %}
<div class='text-dark p-3'>
    <h1>Welcome {{ request.user.username}} to news</h1>
</div>
{% if request.user.rol.name == 'system_admin' %}
<div>
  <a href="{% url 'news:add_news' %}"><button class="btn btn-outline-primary mt-4 mx-4" type="submit">Add news</button></a>
</div>
{% endif %}

{% for new in news %}
<div class="container text-center py-4">
    <div class="card" style="width: 18rem;">
        <img src="{{ new.news_image.url }}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">{{ new.title }}</h5>
          <p class="card-text">{{ new.description }}</p>
          <a href="{% url 'news:detail' new.id %}" class="btn btn-primary">More</a>
        </div>
    </div>
</div>

<br><br>
{% endfor %}
{% endblock %}