website/main/urls.py
from django.urls import path


from . import views


app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

website/stores/urls.py
from django.urls import path


from . import views

app_name = 'stores'

urlpatterns = [
    path('stores/', views.stores, name='stores'),
    path('add_store/', views.addin_store, name='add_store'),
    path('stores/edit/<int:pk>/', views.edit, name='edit'),
    path('stores/delete/<int:pk>/', views.delete, name='delete'),
]

website/website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('users.urls')),
    path('', include('main.urls')),
    path('', include('news.urls')),
    path('', include('stores.urls')),
    path('', include('profiles.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/stores/models.py
from django.db import models

class Store(models.Model):
    name = models.CharField(max_length=70)
    manager = models.CharField(max_length=50)
    address = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created_at',)

    def __str__(self) -> str:
        return self.name

website/stores/forms.py
from django import forms


from .models import Store

CLASS_INPUT = 'form-control w-full rounded-xl border mb-4 mt-2'

class StoreForm(forms.ModelForm):
    class Meta:
        model = Store
        fields = ['name', 'manager', 'address']

        widgets = {
            'name': forms.TextInput(attrs={
            'class': CLASS_INPUT
            }),
            'manager': forms.TextInput(attrs={
            'class': CLASS_INPUT
            }),

            'address': forms.Textarea(attrs={
            'class': CLASS_INPUT
            }),
        }

website/stores/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required

from .models import Store
from .forms import StoreForm

@login_required
def stores(request):

    stores = Store.objects.all()

    return render(request, 'stores/stores.html', {
        'stores': stores,
    })

@login_required
def addin_store(request):
    if not request.user.is_authenticated:
        return redirect('/')
    
    if request.method == 'POST':
        form = StoreForm(request.POST)

        if form.is_valid():
            # store = form.save(commit=False)
            form.save()
            return redirect('stores:stores')
    
    else:
        form = StoreForm()

    return render(request, 'stores/add_store.html', {
        'form': form
    })


def edit(request, pk):
    if not request.user.is_authenticated:
        return redirect('/')
    
    stores = get_object_or_404(Store, pk=pk)

    if request.method == 'POST':
        form = StoreForm(request.POST, instance=stores)
        if form.is_valid():
            form.save()

            return redirect('stores:stores')
    else:
        form = StoreForm(instance=stores)

    return render(request, 'stores/add_store.html', {
        'form': form
    })


@login_required
def delete(request, pk):
    if not request.user.is_authenticated:
        return redirect('stores:stores')
    
    store = get_object_or_404(Store, pk=pk)
    store.delete()
    return redirect('stores:stores')
    

website/stores/templates/stores/add_store.html
{% extends 'main/base.html' %}

{% block title %} Add store {% endblock %}

{% block content %}
{% if request.user.rol.name != 'system_admin' %}
<h1 class="p-3">{{ request.user.username }} you can't add the store</h1>
{% endif %}
<div class="mb-3">
    <div class="px-4 py-4">
        <form method="POST">
            {% csrf_token %}
            {{ form }}
            <button class="btn btn-outline-success mt-4 mx-4" type="submit">submit</button>
        </form>
    </div>
</div>

<br>

{% endblock %}

website/stores/templates/stores/stores.html
{% extends 'main/base.html' %}

{% block title %} Stores {% endblock %}

{% block content %}
<style>body a{text-decoration:none; color:black;} </style>
<div class='p-3'>
  <h3>Welcome  {{ request.user.first_name }} {{ request.user.last_name }}. you cat see the information about the stores</h3>
</div>
{% if request.user.rol.name == 'system_admin' %}
<div>
  <a href="{% url 'stores:add_store' %}"><button class="btn btn-outline-primary mt-4 mx-4" type="submit">Add store</button></a>
</div>
{% endif %}


<div class="container text-center">
    <div class="row py-4 px-4">
      <div class="col bg-primary">
        Name
      </div>
      <div class="col bg-primary">
        Address
      </div>
      <div class="col bg-primary">
        Manager
      </div>
      {% if request.user.rol.name == 'system_admin' %}
      <div class="col bg-primary">
        Delete
      </div>
      {% endif %}
    </div>
  </div>
{% for store in stores %}
<div class="container text-center">
    <div class="row py-4 px-4">
      <div class="col">
        {% if request.user.rol.name == 'system_admin' %}
        <a href="{% url 'stores:edit' store.id %}">{{ store.name }}</a>
        {% else %}
        {{ store.name }}
        {% endif %}
      </div>
      <div class="col">
        {{ store.address }}
      </div>
      <div class="col">
        {{ store.manager }}
      </div>
      {% if request.user.rol.name == 'system_admin' %}
      <div class="col">
        <a href="{% url 'stores:delete' store.id %}"><button type="button" class="btn-close" aria-label="Close"></button></a>
      </div>
      {% endif %}
    </div>
  </div>
{% endfor %}

{% for i in stores %}
<br>
{% endfor %}

{% endblock %}