website/main/urls.py
from django.urls import path


from . import views


app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

website/users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.custom_login, name='login'),
    path('logout/', views.custom_logout, name='logout'),
    path('employees/', views.employess, name='employees'),
    path('add_user/', views.add_user, name='add_user'),


]

website/website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('users.urls')),
    path('', include('main.urls')),
    path('', include('news.urls')),
    path('', include('stores.urls')),
    path('', include('profiles.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from stores.models import Store

class Rol(models.Model):
    name = models.CharField(max_length=30)
    def __str__(self) -> str:
        return self.name



class CustomUser(AbstractUser):

    profile_image = models.ImageField(upload_to='media/images/profile', null=True, blank=True)
    store = models.ForeignKey(Store, related_name='users', null=True, on_delete=models.CASCADE)
    job = models.CharField(max_length=20)
    rol = models.ForeignKey(Rol, related_name='users', null=True, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created_at',)

    def __str__(self) -> str:
        return self.username

website/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model




class UserAddingForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'username', 'password1', 'password2', 'profile_image', 'store', 'job', 'rol']

        widgets = {
            'first_name': forms.TextInput(attrs={
            'class': 'form-control w-full rounded-xl border'
            }),
            'last_name': forms.TextInput(attrs={
            'class': 'form-control w-full rounded-xl border'
            }),

            'username': forms.TextInput(attrs={
            'class': 'form-control w-full rounded-xl border'
            }),

            'password1': forms.PasswordInput(attrs={
            'class': 'form-control w-full rounded-xl border'
            }),

            'password2': forms.PasswordInput(attrs={
            'class': 'form-control w-full rounded-xl border'
            }),

            'profile_image': forms.FileInput(attrs={
            'class': 'form-control w-full rounded-xl border'
            }),
            'store': forms.Select(attrs={
            'class': 'form-control w-full rounded-xl border'
            }),
            'job': forms.TextInput(attrs={
            'class': 'form-control w-full rounded-xl border'
            }),

            'rol': forms.Select(attrs={
            'class': 'form-control w-full rounded-xl border'
            }),
            

            
            

        }

        def save(self, commit=True):
            user = super(UserAddingForm, self).save(commit=False)
            if commit:
                user.save()

            return user
        

website/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, authenticate, get_user_model
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm

from .forms import UserAddingForm
from .models import CustomUser


@login_required
def custom_logout(request):
    logout(request)
    return redirect("main:home")


def custom_login(request):
    if request.user.is_authenticated:
        return redirect('main:home')
    
    if request.method == 'POST':
        form = AuthenticationForm(request=request, data=request.POST)
        if form.is_valid():
            user = authenticate(
                username = form.cleaned_data["username"],
                password = form.cleaned_data["password"],
            )
            if user is not None:
                login(request, user)
                if request.user.is_authenticated:
                    return redirect('main:home')
        # else:
        #     for error in list(form.errors.values()):
        #         messages.error(request, 'Not login')

    form = AuthenticationForm()

    return render(request, 'users/login.html', {
        'form': form
    })


@login_required
def employess(request):
    employeeses = CustomUser.objects.all()

    return render(request, 'users/employees.html', {
        'employeeses': employeeses
    })


@login_required
def add_user(request):
    if not request.user.is_authenticated:
        return redirect('/')
    
    if request.method == 'POST':
        form = UserAddingForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            return redirect('users:employees') 
        
        else:
            for error in list(form.errors.values()):
                messages.error(request, error)

    else:
        form = UserAddingForm()
    
    return render(request, 'users/add_user.html', {
        'form': form,
    })

website/users/templates/users/add_user.html
{% extends 'main/base.html' %}
{% block title %} Add user {% endblock %}

{% block content %}

<div class="mb-3">
    <div class="px-4 py-4">
        <h1>Adding user</h1>
        <hr>
    </div>
    {% if request.user.rol.name == 'system_admin' %}
    <div class="px-4">
        <form method="POST" action="." enctype="multipart/form-data">
            {% csrf_token %} 
            {{ form.as_p }}
            <button class="btn btn-outline-success mt-4 mx-4" type="submit">submit</button>
        </form>
    </div>
</div>


<br><br><br><br><br><br>
{% else %}
<h1>{{ request.user.username }} you can't add user</h1>
{% endif %}
{% endblock %}

website/users/templates/users/employees.html
{% extends 'main/base.html' %}

{% block title %} employees {% endblock %}

{% block content %}
{% if request.user.rol.name == 'system_admin' %}
<a href="{% url 'users:add_user' %}"><button class="btn btn-outline-info mt-4 mx-4" type="submit">Add user</button></a>
{% endif %}
<div class="container text-center">
    <div class="row py-4 px-4">
      <div class="col bg-primary">
        Name
      </div>
      <div class="col bg-primary">
        Branchnam
      </div>
      <div class="col bg-primary">
        Rol
      </div>
    </div>
  </div>
{% for employees in employeeses %}
{% if employees.username == 'test' %}

{% else %}
<div class="container text-center">
    <div class="row py-4 px-4">
      <div class="col">
        {{ employees.first_name }} | {{ employees.last_name }}
      </div>
      <div class="col">
        {{ employees.store.name }}
      </div>
      <div class="col">
        {{ employees.rol.name }}
      </div>
    </div>
  </div>
{% endif %}
{% endfor %}
{% endblock %}

website/users/templates/users/login.html
{% extends 'main/base.html' %}

{% block title %} Login {% endblock %}

{% block content %}
<div class="mb-3 text-center">
    <div class="px-4 py-4">
        <form action="." method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-outline-info" type="submit">Login</button>
        </form>
    </div>
</div>


{% endblock %}